video_1_transcript = [
    {
        'id': '0',
        'content': 'AI is already applied in everyday life, used in social media face filters, facial recognition, content recommendation, and language translating technology.',
        'start_timestamp': '00:00:00.640',
        'end_timestamp': '00:00:10.120',
        'current_aoi_list': [2],
    },
    {
        'id': '1',
        'content': 'For example, AI is used for social media face filters by identifying key points on a person\'s face, or face landmarks, such as the eyes, nose, and mouth.',
        'start_timestamp': '00:00:10.120',
        'end_timestamp': '00:00:21.529',
        'current_aoi_list': [3],
    },
    {
        'id': '2',
        'content': 'Once these points have been identified, the contours of the face can be pinpointed, and the filter can be applied onto the user\'s face.',
        'start_timestamp': '00:00:21.529',
        'end_timestamp': '00:00:29.595',
        'current_aoi_list': [4,5],
    },
    {
        'id': '3',
        'content': 'The beginning of AI research dates back to the 1950s.',
        'start_timestamp': '00:00:29.595',
        'end_timestamp': '00:00:32.810',
        'current_aoi_list': [2,3],
    },
    {
        'id': '4',
        'content': 'Alan Turing, a notable computer scientist known for the breaking of the Enigma code in World War II, published a paper suggesting the testing of a “thinking” machine that could hold a conversation with a human as if it were just another person.',
        'start_timestamp': '00:00:32.810',
        'end_timestamp': '00:00:47.020',
        'current_aoi_list': [2,3],
    },
    {
        'id': '5',
        'content': 'Turing\'s papers and their discussion sparked the concept of artificial intelligence.',
        'start_timestamp': '00:00:47.020',
        'end_timestamp': '00:00:52.520',
        'current_aoi_list': [2,3],
    },
    {
        'id': '6',
        'content': 'While artificial intelligence was an exciting, futuristic concept in the 1950s, by the 1970s, AI research funding was cut due to many reports stating a lack of progress and success.',
        'start_timestamp': '00:00:52.520',
        'end_timestamp': '00:01:05.250',
        'current_aoi_list': [4,5],
    },
    {
        'id': '7',
        'content': 'The late 1970s became known as the first AI winter.',
        'start_timestamp': '00:01:05.250',
        'end_timestamp': '00:01:10.869',
        'current_aoi_list': [4,5],
    },
    {
        'id': '8',
        'content': 'The first AI winter ended in the early 1980s after several new developments.',
        'start_timestamp': '00:01:10.869',
        'end_timestamp': '00:01:16.200',
        'current_aoi_list': [4,5],
    },
    {
        'id': '9',
        'content': 'One of these developments was the US increasing funding for AI again.',
        'start_timestamp': '00:01:16.200',
        'end_timestamp': '00:01:21.100',
        'current_aoi_list': [6,7],
    },
    {
        'id': '10',
        'content': 'Japan had started a new fifth generation computer project and the US aimed to compete to become a world leader in computer science.',
        'start_timestamp': '00:01:21.100',
        'end_timestamp': '00:01:29.299',
        'current_aoi_list': [6,7],
    },
    {
        'id': '11',
        'content': 'Another development was the introduction of “Expert Systems” which was quickly utilized by large global corporations.',
        'start_timestamp': '00:01:29.299',
        'end_timestamp': '00:01:35.530',
        'current_aoi_list': [6,7],
    },
    {
        'id': '12',
        'content': 'The 1980s marked the end of the first AI winter with the promising introduction of Expert Systems.',
        'start_timestamp': '00:01:35.530',
        'end_timestamp': '00:01:43.400',
        'current_aoi_list': [6,7],
    },
    {
        'id': '13',
        'content': 'The Expert system operated within a clearly defined area of knowledge and followed strict logic rules.',
        'start_timestamp': '00:01:43.400',
        'end_timestamp': '00:01:50.410',
        'current_aoi_list': [6,7],
    },
    {
        'id': '14',
        'content': 'Even with such restrictions, these programs proved useful to corporations.',
        'start_timestamp': '00:01:50.410',
        'end_timestamp': '00:01:55.750',
        'current_aoi_list': [6,7],
    },
    {
        'id': '15',
        'content': 'However, despite the success of the Expert system, computer science experienced a second AI winter starting in 1987.',
        'start_timestamp': '00:01:55.750',
        'end_timestamp': '00:02:05.899',
        'current_aoi_list': [6,7],
    },
    {
        'id': '16',
        'content': 'Expert system computers were seen as slow, bulky, and not user friendly, and were becoming too expensive and difficult to update compared to the new desktop computer.',
        'start_timestamp': '00:02:05.899',
        'end_timestamp': '00:02:15.900',
        'current_aoi_list': [6,7],
    },
    {
        'id': '17',
        'content': 'As consumers no longer needed to buy an expensive machine specialized for running expert systems, this led to the collapse of the market for specialized AI hardware in 1987.',
        'start_timestamp': '00:02:15.900',
        'end_timestamp': '00:02:26.140',
        'current_aoi_list': [6,7],
    },
    {
        'id': '18',
        'content': 'Thus, an entire industry worth half a billion dollars was replaced in a single year. Research funding was once again cut.',
        'start_timestamp': '00:02:26.140',
        'end_timestamp': '00:02:35.370',
        'current_aoi_list': [6,7],
    },
    {
        'id': '19',
        'content': 'It wasn\'t until 1997 when IBM\'s Deep Blue defeated chess champion Garry Kasparov that the general public realized the power of AI.',
        'start_timestamp': '00:02:35.370',
        'end_timestamp': '00:02:46.170',
        'current_aoi_list': [8,9],
    },
    {
        'id': '20',
        'content': 'With the breakthrough in hardware equipment, the computer\'s processing power and storage capacity grew exponentially, enabling companies to store and process large amounts of data.',
        'start_timestamp': '00:02:46.170',
        'end_timestamp': '00:02:56.840',
        'current_aoi_list': [8,9],
    },
    {
        'id': '21',
        'content': 'Various companies and government agencies have successfully applied AI on a larger scale in different applications. This leads to a new round of growth in AI.',
        'start_timestamp': '00:02:56.840',
        'end_timestamp': '00:03:07.799',
        'current_aoi_list': [8,9],
    },
    {
        'id': '22',
        'content': 'The 2010s saw the rise of digital virtual assistants.',
        'start_timestamp': '00:03:07.799',
        'end_timestamp': '00:03:12.600',
        'current_aoi_list': [10,11],
    },
    {
        'id': '23',
        'content': 'Assistants like Alexa, Siri, and Google utilize natural language processing to act as a convenient source of information for users, doing many of the tasks a human assistant would.',
        'start_timestamp': '00:03:12.600',
        'end_timestamp': '00:03:23.769',
        'current_aoi_list': [10,11],
    },
    {
        'id': '24',
        'content': 'Virtual assistants like these are the future of AI. They are controlling autonomous cars and taking a physical form as a robot.',
        'start_timestamp': '00:03:23.769',
        'end_timestamp': '00:03:32.420',
        'current_aoi_list': [10,11],
    },
    {
        'id': '25',
        'content': 'Artificial intelligence has come a long way since Alan Turing\'s idea in a hypothetical paper, and it will continue into the future driving cars, walking around in everyday life, and more.',
        'start_timestamp': '00:03:32.420',
        'end_timestamp': '00:03:43.590',
        'current_aoi_list': [2,3,12],
    },
    {
        'id': '26',
        'content': 'Artificial Intelligence Definitions: But still, what is AI?',
        'start_timestamp': '00:03:43.590',
        'end_timestamp': '00:03:45.409',
        'current_aoi_list': [1],
    },
    {
        'id': '27',
        'content': 'AI usually does not have one explicit definition.',
        'start_timestamp': '00:03:45.409',
        'end_timestamp': '00:03:48.110',
        'current_aoi_list': [1],
    },
    {
        'id': '28',
        'content': 'However, it can be defined as a sector of computer science that allows computers to solve problems through making predictions and decisions.',
        'start_timestamp': '00:03:48.110',
        'end_timestamp': '00:03:55.180',
        'current_aoi_list': [2],
    },
    {
        'id': '29',
        'content': 'The sector of AI where AI currently is adopted in products is called machine learning, or ML.',
        'start_timestamp': '00:03:57.180',
        'end_timestamp': '00:04:03.750',
        'current_aoi_list': [3],
    },
    {
        'id': '30',
        'content': 'Machine learning teaches computers how to make problem-solving predictions and decisions by teaching them to learn from collected data.',
        'start_timestamp': '00:04:03.750',
        'end_timestamp': '00:04:11.451',
        'current_aoi_list': [3],
    },
    {
        'id': '31',
        'content': 'As seen in the diagram, artificial intelligence is a branch of computer science, and machine learning is a branch of artificial intelligence.',
        'start_timestamp': '00:04:11.451',
        'end_timestamp': '00:04:19.500',
        'current_aoi_list': [4],
    },
    {
        'id': '32',
        'content': 'As our focus will be on machine learning, now let us have a look at this field in AI from a high level.',
        'start_timestamp': '00:04:19.500',
        'end_timestamp': '00:04:25.080',
        'current_aoi_list': [1,2],
    },
    {
        'id': '33',
        'content': 'Usually, machine learning problems and its related solutions can be divided into three categories. We will have a look at each category.',
        'start_timestamp': '00:04:25.080',
        'end_timestamp': '00:04:32.370',
        'current_aoi_list': [3],
    },
]


video_2_transcript = [
    {
        'id': '0',
        'content': 'The most straightforward way of learning is called supervised learning, also known as supervised machine learning.',
        'start_timestamp': '00:00:01.200',
        'end_timestamp': '00:00:05.960',
        'current_aoi_list': [1],
    },
    {
        'id': '1',
        'content': 'Supervised learning deals with the problems that are trying to find a relationship that guides an input to an output based on given examples of input-output pairs.',
        'start_timestamp': '00:00:05.960',
        'end_timestamp': '00:00:15.680',
        'current_aoi_list': [2],
    },
    {
        'id': '2',
        'content': 'Each input-output pair can be understood as a question-answer pair when you learn math.',
        'start_timestamp': '00:00:15.680',
        'end_timestamp': '00:00:21.640',
        'current_aoi_list': [2],
    },
    {
        'id': '3',
        'content': 'By showing the computer with many example pairs, we expect it can understand how to generate an output given some new input.',
        'start_timestamp': '00:00:21.640',
        'end_timestamp': '00:00:32.800',
        'current_aoi_list': [2],
    },
    {
        'id': '4',
        'content': 'Let\'s consider this example. In a fruit packaging factory, we would like to find an automated way to separate the different kinds of fruit, Apple, blueberry, and banana, into three different boxes for shipment.',
        'start_timestamp': '00:00:32.800',
        'end_timestamp': '00:00:44.880',
        'current_aoi_list': [3],
    },
    {
        'id': '5',
        'content': 'A digital system can take pictures of each fruit traveling down the conveyor belt and must use the image input to identify the fruit with its name for its proper shipment box destination.',
        'start_timestamp': '00:00:44.880',
        'end_timestamp': '00:00:56.800',
        'current_aoi_list': [3,4],
    },
    {
        'id': '6',
        'content': 'In this example, the input to the system is pictures of fruits, and the output expected from the system is the category of the fruit.',
        'start_timestamp': '00:00:56.800',
        'end_timestamp': '00:01:04.240',
        'current_aoi_list': [3,4,6],
    },
    {
        'id': '7',
        'content': 'The relationship we would like to find is how to identify the fruit category given the pictures taken.',
        'start_timestamp': '00:01:04.240',
        'end_timestamp': '00:01:08.920',
        'current_aoi_list': [3,5],
    },
    {
        'id': '8',
        'content': 'The input-output pairs we would provide to the system would then be the image of a fruit and a label saying what fruit is inside the image.',
        'start_timestamp': '00:01:08.920',
        'end_timestamp': '00:01:19.560',
        'current_aoi_list': [3,6],
    },
    {
        'id': '9',
        'content': 'Each time the picture-fruit-name pair is fed to the system, we expect the model to discover the underlying relationship between picture and fruits, and gradually the system improves the model\'s performance.',
        'start_timestamp': '00:01:19.560',
        'end_timestamp': '00:01:32.360',
        'current_aoi_list': [3,4,6],
    },
    {
        'id': '10',
        'content': 'This procedure of adjusting our system based on data is called learning or training.',
        'start_timestamp': '00:01:32.360',
        'end_timestamp': '00:01:38.760',
        'current_aoi_list': [4],
    },
    {
        'id': '11',
        'content': 'After training, we will apply the system to the conveyor belt, with new pictures of apples, blueberries, and bananas, to see if the model can provide the correct output.',
        'start_timestamp': '00:01:38.760',
        'end_timestamp': '00:01:48.680',
        'current_aoi_list': [5,6],
    },
    {
        'id': '12',
        'content': 'This is called prediction. So why is supervised learning feasible in this example?',
        'start_timestamp': '00:01:48.680',
        'end_timestamp': '00:01:55.280',
        'current_aoi_list': [1,2], # slide 2
    },
    {
        'id': '13',
        'content': 'Why can images of apples be identified as one thing and images of blueberries can be identified separately?',
        'start_timestamp': '00:01:55.280',
        'end_timestamp': '00:02:00.320',
        'current_aoi_list': [2,5],
    },
    {
        'id': '14',
        'content': 'This is because the apples are similar to each other just like the blueberries are similar to each other.',
        'start_timestamp': '00:02:00.320',
        'end_timestamp': '00:02:06.600',
        'current_aoi_list': [2,5],
    },
    {
        'id': '15',
        'content': 'And apples and blueberries are different in some aspects.',
        'start_timestamp': '00:02:06.600',
        'end_timestamp': '00:02:10.520',
        'current_aoi_list': [2,5],
    },
    {
        'id': '16',
        'content': 'In fact, these similar or different aspects are what a system has to pay attention to.',
        'start_timestamp': '00:02:10.520',
        'end_timestamp': '00:02:14.760',
        'current_aoi_list': [2],
    },
    {
        'id': '17',
        'content': 'Such aspects are called features, which are characteristics of objects, they are selected to make all the inputs widely different from each other.',
        'start_timestamp': '00:02:14.760',
        'end_timestamp': '00:02:24.240',
        'current_aoi_list': [3],
    },
    {
        'id': '18',
        'content': 'In this instance, useful features are colors and textures, and unreliable features are “round shape” and “not sparkly” because both apples and blueberries are round and not sparkly.',
        'start_timestamp': '00:02:24.240',
        'end_timestamp': '00:02:35.320',
        'current_aoi_list': [3,5],
    },
    {
        'id': '19',
        'content': 'Both apples and blueberries share these characteristics and they would not be helpful in distinguishing the two.',
        'start_timestamp': '00:02:35.320',
        'end_timestamp': '00:02:43.560',
        'current_aoi_list': [3,5],
    },
    {
        'id': '20',
        'content': 'We may ask, what should good features look like? The samples have to be quite different in this feature.',
        'start_timestamp': '00:02:43.560',
        'end_timestamp': '00:02:49.080',
        'current_aoi_list': [3],
    },
    {
        'id': '21',
        'content': 'Color is a good feature because apples and blueberries are different in colors.',
        'start_timestamp': '00:02:49.080',
        'end_timestamp': '00:02:53.560',
        'current_aoi_list': [3,5],
    },
    {
        'id': '22',
        'content': 'In addition, the feature is supposed to be highly correlated with the target sample.',
        'start_timestamp': '00:02:53.560',
        'end_timestamp': '00:02:59.280',
        'current_aoi_list': [3],
    },
    {
        'id': '23',
        'content': 'A feature like the age of the fruit is irrelevant because fruits do not have age!',
        'start_timestamp': '00:02:59.280',
        'end_timestamp': '00:03:04.040',
        'current_aoi_list': [3,5],
    },
    {
        'id': '24',
        'content': 'Labels are the thing we are trying to predict based on an input.',
        'start_timestamp': '00:03:04.040',
        'end_timestamp': '00:03:08.000',
        'current_aoi_list': [4],
    },
    {
        'id': '25',
        'content': 'Using the fruit example, the label would be the type of fruit predicted based on the image input: apples, blueberries, or bananas.',
        'start_timestamp': '00:03:08.000',
        'end_timestamp': '00:03:15.120',
        'current_aoi_list': [4,5],
    },
    {
        'id': '26',
        'content': 'The system now notes useful features in the input image.',
        'start_timestamp': '00:03:15.120',
        'end_timestamp': '00:03:18.480',
        'current_aoi_list': [3],
    },
    {
        'id': '27',
        'content': 'If the fruit in the image is red, the algorithm would be able to label the inputted image as an apple.',
        'start_timestamp': '00:03:18.480',
        'end_timestamp': '00:03:25.120',
        'current_aoi_list': [4,5],
    },
    {
        'id': '28',
        'content': 'But computers do not understand quantitative descriptions such as colors or shapes.',
        'start_timestamp': '00:03:25.120',
        'end_timestamp': '00:03:30.060',
        'current_aoi_list': [1,2], # slide 3
    },
    {
        'id': '29',
        'content': 'Computers only understand numbers. So we have to translate the previous ideas into mathematical descriptions.',
        'start_timestamp': '00:03:30.060',
        'end_timestamp': '00:03:36.520',
        'current_aoi_list': [1,2],
    },
    {
        'id': '30',
        'content': 'For example, consider how we would describe an apple.',
        'start_timestamp': '00:03:36.520',
        'end_timestamp': '00:03:40.000',
        'current_aoi_list': [2],
    },
    {
        'id': '31',
        'content': 'We would like first to describe its color. Then the first number in the vector will represent colors.',
        'start_timestamp': '00:03:40.000',
        'end_timestamp': '00:03:46.080',
        'current_aoi_list': [2],
    },
    {
        'id': '32',
        'content': 'We may use 0 to represent red, and 1 for navy blue, and 2 for green, etc.',
        'start_timestamp': '00:03:46.080',
        'end_timestamp': '00:03:52.000',
        'current_aoi_list': [2],
    },
    {
        'id': '33',
        'content': 'In the second number, we may describe the shape of the fruit.',
        'start_timestamp': '00:03:52.000',
        'end_timestamp': '00:03:56.040',
        'current_aoi_list': [2],
    },
    {
        'id': '34',
        'content': 'We can use 0 for a round shape, 1 for an oval shape, and 2 for a curved shape.',
        'start_timestamp': '00:03:56.040',
        'end_timestamp': '00:04:02.440',
        'current_aoi_list': [2],
    },
    {
        'id': '35',
        'content': 'This ordered collection of numbers is called a vector, and it describes the features we would like the system to take.',
        'start_timestamp': '00:04:02.440',
        'end_timestamp': '00:04:09.040',
        'current_aoi_list': [2],
    },
    {
        'id': '36',
        'content': 'The input data is usually represented by x and we use a subscript to distinguish each different feature.',
        'start_timestamp': '00:04:09.040',
        'end_timestamp': '00:04:15.520',
        'current_aoi_list': [2],
    },
    {
        'id': '37',
        'content': 'Here, the x_1 would be color and x_2 would be the shape. We then translate the labels.',
        'start_timestamp': '00:04:15.520',
        'end_timestamp': '00:04:25.520',
        'current_aoi_list': [2,4],
    },
    {
        'id': '38',
        'content': 'In this example, we can use 0 for apples, 1 for blueberries, and 2 for bananas. But the output can also be real numbers.',
        'start_timestamp': '00:04:25.520',
        'end_timestamp': '00:04:34.040',
        'current_aoi_list': [4],
    },
    {
        'id': '39',
        'content': 'For example, we can ask the model to generate the weight of the apple given the image of the apple,',
        'start_timestamp': '00:04:34.040',
        'end_timestamp': '00:04:39.000',
        'current_aoi_list': [2,3],
    },
    {
        'id': '40',
        'content': 'so we could further understand the quality of apples and sell them at different prices.',
        'start_timestamp': '00:04:39.000',
        'end_timestamp': '00:04:45.000',
        'current_aoi_list': [2,3],
    },
    {
        'id': '41',
        'content': 'Now we can use mathematical equations to describe this relationship.',
        'start_timestamp': '00:04:45.000',
        'end_timestamp': '00:04:48.560',
        'current_aoi_list': [5],
    },
    {
        'id': '42',
        'content': 'We can start with a very simple math equation: y = 1 + 0.5 x1 + 0.5 x2.',
        'start_timestamp': '00:04:48.560',
        'end_timestamp': '00:04:58.560',
        'current_aoi_list': [5],
    },
    {
        'id': '43',
        'content': 'We use the input to calculate the output generated by our system, that would be 1, 1.5, 2, and 2.',
        'start_timestamp': '00:04:58.560',
        'end_timestamp': '00:05:07.840',
        'current_aoi_list': [5],
    },
    {
        'id': '44',
        'content': 'We notice the model does not provide the correct answer now but it is fine.',
        'start_timestamp': '00:05:07.840',
        'end_timestamp': '00:05:12.600',
        'current_aoi_list': [4,5],
    },
    {
        'id': '45',
        'content': 'We can change the equation to make the output from the model to be closer to the label.',
        'start_timestamp': '00:05:12.600',
        'end_timestamp': '00:05:16.240',
        'current_aoi_list': [5,6],
    },
    {
        'id': '46',
        'content': 'This is the goal of supervised learning: to minimize the difference between the generated output from the model with the label.',
        'start_timestamp': '00:05:16.240',
        'end_timestamp': '00:05:23.640',
        'current_aoi_list': [6],
    },
]

video_3_transcript = [
    {
        'id': '0',
        'content': 'But in many cases, often large amounts of data are available, but no labels are present.',
        'start_timestamp': '00:00:00.280',
        'end_timestamp': '00:00:05.360',
        'current_aoi_list': [1,2,3,4,5,6],
    },
    {
        'id': '1',
        'content': 'For example, medical devices such as a CAT scanner, MRI scanner, or an EKG, produce streams of data but these are entirely unlabeled.',
        'start_timestamp': '00:00:05.360',
        'end_timestamp': '00:00:15.550',
        'current_aoi_list': [1,2,3,4,5,6],
    },
    {
        'id': '2',
        'content': 'They do not contain the information of which part is indicating what disease.',
        'start_timestamp': '00:00:15.550',
        'end_timestamp': '00:00:20.600',
        'current_aoi_list': [1,2,3,4,5,6],
    },
    {
        'id': '3',
        'content': 'In these cases obtaining labeled data is difficult, costly, or impossible, and so supervised learning methods are not possible.',
        'start_timestamp': '00:00:20.600',
        'end_timestamp': '00:00:28.840',
        'current_aoi_list': [1,2,3,4,5,6],
    },
    {
        'id': '4',
        'content': 'This gives rise to unsupervised learning.',
        'start_timestamp': '00:00:28.840',
        'end_timestamp': '00:00:32.560',
        'current_aoi_list': [1,2],
    },
    {
        'id': '5',
        'content': 'Unsupervised learning describes a family of algorithms that learns patterns from unlabelled data.',
        'start_timestamp': '00:00:32.560',
        'end_timestamp': '00:00:37.540',
        'current_aoi_list': [2],
    },
    {
        'id': '6',
        'content': 'This is in contrast to supervised learning techniques where a model is given a training set of inputs and a set of observations and must learn a function from the inputs to the observations.',
        'start_timestamp': '00:00:37.540',
        'end_timestamp': '00:00:48.400',
        'current_aoi_list': [3],
    },
    {
        'id': '7',
        'content': 'In unsupervised learning, only the inputs are available, and a model must look for interesting patterns in the data.',
        'start_timestamp': '00:00:48.400',
        'end_timestamp': '00:00:56.560',
        'current_aoi_list': [2,3],
    },
    {
        'id': '8',
        'content': 'The machine is forced to build a compact internal representation of its given input data and use such representation to complete the requested tasks.',
        'start_timestamp': '00:00:56.560',
        'end_timestamp': '00:01:07.680',
        'current_aoi_list': [2,3,5],
    },
    {
        'id': '9',
        'content': 'The two main subcategories of unsupervised learning we will be discussing today are anomaly detection and clustering.',
        'start_timestamp': '00:01:07.680',
        'end_timestamp': '00:01:17.120',
        'current_aoi_list': [2,3],
    },
    {
        'id': '10',
        'content': 'One widely adopted use case for unsupervised learning is anomaly detection.',
        'start_timestamp': '00:01:17.120',
        'end_timestamp': '00:01:23.640',
        'current_aoi_list': [1], # slide 2
    },
    {
        'id': '11',
        'content': 'It is generally understood to be the identification of rare items, events, or observations that deviate significantly from the majority of the data and do not conform to normal behavior.',
        'start_timestamp': '00:01:23.640',
        'end_timestamp': '00:01:35.500',
        'current_aoi_list': [2],
    },
    {
        'id': '12',
        'content': 'Looking at the graph to the left, most of the data points follow a nonlinear, increasing line.',
        'start_timestamp': '00:01:35.500',
        'end_timestamp': '00:01:41.000',
        'current_aoi_list': [3],
    },
    {
        'id': '13',
        'content': 'The one exception is the point at (30,6000).',
        'start_timestamp': '00:01:41.000',
        'end_timestamp': '00:01:45.440',
        'current_aoi_list': [3],
    },
    {
        'id': '14',
        'content': 'This point deviates significantly from the pattern of the rest of the data, and would be considered an anomaly.',
        'start_timestamp': '00:01:45.440',
        'end_timestamp': '00:01:52.560',
        'current_aoi_list': [3],
    },
    {
        'id': '15',
        'content': 'One example of the use of anomaly detection is with fraud.',
        'start_timestamp': '00:01:52.560',
        'end_timestamp': '00:01:57.600',
        'current_aoi_list': [1,2],
    },
    {
        'id': '16',
        'content': 'With the common use of credit cards, financial fraud has become a major problem.',
        'start_timestamp': '00:01:57.600',
        'end_timestamp': '00:02:02.400',
        'current_aoi_list': [1,2],
    },
    {
        'id': '17',
        'content': 'Unauthorized or fraudulent transactions can sometimes be recognized as a break or an anomaly from the user\'s normal pattern of usages, such as large volume transactions, or rapid buying sprees.',
        'start_timestamp': '00:02:02.400',
        'end_timestamp': '00:02:15.760',
        'current_aoi_list': [1,2],
    },
    {
        'id': '18',
        'content': 'Credit card transaction data can be fed into an anomaly detection algorithm in the form of a vector, which is a collection of numbers, such as transaction amount, transaction time of day, transaction location, and time since the previous transaction.',
        'start_timestamp': '00:02:15.760',
        'end_timestamp': '00:02:31.020',
        'current_aoi_list': [1,2,3],
    },
    {
        'id': '19',
        'content': 'The outliers can then be flagged to the bank as potentially fraudulent.',
        'start_timestamp': '00:02:31.020',
        'end_timestamp': '00:02:36.280',
        'current_aoi_list': [1,2,3],
    },
    {
        'id': '20',
        'content': 'In these cases, the bank can either unilaterally block the card or request the user to authenticate the transaction in another way.',
        'start_timestamp': '00:02:36.280',
        'end_timestamp': '00:02:44.160',
        'current_aoi_list': [1,2,3],
    },
    {
        'id': '21',
        'content': 'Anomaly detection algorithms, however, may not always be accurate.',
        'start_timestamp': '00:02:44.160',
        'end_timestamp': '00:02:50.400',
        'current_aoi_list': [4],
    },
    {
        'id': '22',
        'content': 'Sometimes, a normal datapoint may be flagged as an anomaly, a false positive, or an anomalous data point is mistaken as normal and overlooked, a false negative.',
        'start_timestamp': '00:02:50.400',
        'end_timestamp': '00:02:59.760',
        'current_aoi_list': [4],
    },
    {
        'id': '23',
        'content': 'For example, when looking at cancer diagnoses, a false positive would be if cancer was detected in a patient that does not have cancer.',
        'start_timestamp': '00:02:59.760',
        'end_timestamp': '00:03:07.880',
        'current_aoi_list': [4],
    },
    {
        'id': '24',
        'content': 'A false negative would be if cancer was not detected in a patient that does have cancer.',
        'start_timestamp': '00:03:07.880',
        'end_timestamp': '00:03:13.440',
        'current_aoi_list': [4],
    },
    {
        'id': '25',
        'content': 'These inaccuracies can have consequences.',
        'start_timestamp': '00:03:13.440',
        'end_timestamp': '00:03:16.760',
        'current_aoi_list': [4],
    },
    {
        'id': '26',
        'content': 'In this situation, a false positive would cause unnecessary stress and worry for the healthy patient.',
        'start_timestamp': '00:03:16.760',
        'end_timestamp': '00:03:23.280',
        'current_aoi_list': [4],
    },
    {
        'id': '27',
        'content': 'A false negative would be far more damaging, as a sick cancer patient may not seek treatment, mistaking themselves as healthy.',
        'start_timestamp': '00:03:23.280',
        'end_timestamp': '00:03:30.600',
        'current_aoi_list': [4],
    },
    {
        'id': '28',
        'content': 'A false positive, however, is not always the more damaging error.',
        'start_timestamp': '00:03:30.600',
        'end_timestamp': '00:03:34.520',
        'current_aoi_list': [4],
    },
    {
        'id': '29',
        'content': 'In addition, the severity of errors is not always the same: a false negative COVID test is less serious than a false negative cancer diagnosis.',
        'start_timestamp': '00:03:34.520',
        'end_timestamp': '00:03:43.120',
        'current_aoi_list': [4],
    },
    {
        'id': '30',
        'content': 'It is important to assess the situation in which an anomaly detection algorithm is being applied to.',
        'start_timestamp': '00:03:43.120',
        'end_timestamp': '00:03:49.160',
        'current_aoi_list': [4],
    },
    {
        'id': '31',
        'content': 'The algorithm can then be adjusted to favor a false negative over a false positive, or vice versa.',
        'start_timestamp': '00:03:49.160',
        'end_timestamp': '00:03:56.400',
        'current_aoi_list': [4],
    },
    {
        'id': '32',
        'content': 'The end goal of an anomaly detection algorithm is to be as accurate as possible, while also minimizing the risk/cost of false results.',
        'start_timestamp': '00:03:56.400',
        'end_timestamp': '00:04:08.840',
        'current_aoi_list': [5],
    },
    {
        'id': '33',
        'content': 'Clustering is a machine learning problem that aims to group data that have similar properties or features.',
        'start_timestamp': '00:04:08.840',
        'end_timestamp': '00:04:14.680',
        'current_aoi_list': [1,2], # Slide 3
    },
    {
        'id': '34',
        'content': 'Recall the previous medical imaging example, often large amounts of data are available, but no labels for the data are given.',
        'start_timestamp': '00:04:14.680',
        'end_timestamp': '00:04:22.560',
        'current_aoi_list': [3],
    },
    {
        'id': '35',
        'content': 'Doctors have a large amount of imaging data, but they do not know whether the obtained images are associated with what kind of disease.',
        'start_timestamp': '00:04:22.560',
        'end_timestamp': '00:04:30.640',
        'current_aoi_list': [3],
    },
    {
        'id': '36',
        'content': 'In 2019, a team of researchers in the UAE, Egypt, and Australia conducted a meta-study of clustering algorithms on Alzheimer\'s disease data, and reported that it was possible to identify subgroups which corresponded to the stage of the disease\'s progression.',
        'start_timestamp': '00:04:30.640',
        'end_timestamp': '00:04:48.120',
        'current_aoi_list': [3],
    },
    {
        'id': '37',
        'content': 'A number of clustering methods have been applied to datasets and they found that all of the clustering algorithms investigated brought a new level of insight into the various subtypes of Alzheimer\'s patients.',
        'start_timestamp': '00:04:48.120',
        'end_timestamp': '00:05:00.200',
        'current_aoi_list': [3],
    },
    {
        'id': '38',
        'content': 'The clustering techniques allow medical practitioners to identify patterns across patients which would otherwise be difficult to find by eye.',
        'start_timestamp': '00:05:00.200',
        'end_timestamp': '00:05:08.000',
        'current_aoi_list': [3],
    },
    {
        'id': '39',
        'content': 'The blue dots on the left diagram represent all of the input feature vectors.',
        'start_timestamp': '00:05:08.000',
        'end_timestamp': '00:05:13.560',
        'current_aoi_list': [4],
    },
    {
        'id': '40',
        'content': 'The separate green, blue, and red dots on the right diagram represent the same inputs, but now they have been grouped into three separate clusters.',
        'start_timestamp': '00:05:13.560',
        'end_timestamp': '00:05:22.560',
        'current_aoi_list': [5],
    },
    {
        'id': '41',
        'content': 'You want the clusters to be distinct from one another, while also having individual data points within a cluster as similar as possible.',
        'start_timestamp': '00:05:22.560',
        'end_timestamp': '00:05:30.100',
        'current_aoi_list': [5],
    },
    {
        'id': '42',
        'content': 'In other words, you want to maximize the distance between clusters, and minimize the distance between each datapoint and the average point of the cluster to which it is assigned. This is the goal of clustering problems.',
        'start_timestamp': '00:05:30.100',
        'end_timestamp': '00:05:42.360',
        'current_aoi_list': [5],
    },
]

video_4_transcript = [
    {
        'id': '0',
        'content': 'Computer vision is the field of computer science that focuses on creating digital systems that can process, analyze, and make sense of visual data (images or videos) in the same way that humans do.',
        'start_timestamp': '00:00:00.160',
        'end_timestamp': '00:00:11.560',
        'current_aoi_list': [2,3],
    },
    {
        'id': '1',
        'content': 'For example, a system trained to inspect products or watch a production asset can analyze thousands of products in less than a minute, noticing imperceptible defects or issues for humans.',
        'start_timestamp': '00:00:11.560',
        'end_timestamp': '00:00:24.280',
        'current_aoi_list': [4],
    },
    {
        'id': '2',
        'content': 'Computer vision is used in industries ranging from [energy and utilities] to [manufacturing and automotive].',
        'start_timestamp': '00:00:24.280',
        'end_timestamp': '00:00:31.228',
        'current_aoi_list': [4],
    },
    {
        'id': '3',
        'content': 'Scientists and engineers have been trying to develop ways for machines to see and understand visual data for about 60 years.',
        'start_timestamp': '00:00:31.228',
        'end_timestamp': '00:00:37.080',
        'current_aoi_list': [1,12], # Slide 2
    },
    {
        'id': '4',
        'content': 'Experimentation began in 1959 when neurophysiologists showed a cat an array of images, attempting to correlate a response in its brain.',
        'start_timestamp': '00:00:37.080',
        'end_timestamp': '00:00:47.958',
        'current_aoi_list': [2,3],
    },
    {
        'id': '5',
        'content': 'At about the same time, the first computer image scanning technology was developed, enabling computers to digitize and acquire images.',
        'start_timestamp': '00:00:47.958',
        'end_timestamp': '00:00:56.100',
        'current_aoi_list': [4],
    },
    {
        'id': '6',
        'content': 'In 1959, scientists developed equipment that allowed transforming images into grids of numbers—in the language machines could understand.',
        'start_timestamp': '00:00:56.100',
        'end_timestamp': '00:01:05.000',
        'current_aoi_list': [5],
    },
    {
        'id': '7',
        'content': 'And it\'s because of their work that we now can process digital images in various ways.',
        'start_timestamp': '00:01:05.000',
        'end_timestamp': '00:01:12.880',
        'current_aoi_list': [4,5],
    },
    {
        'id': '8',
        'content': 'One of the first digitally scanned photos was the image of the scientist\'s infant son.',
        'start_timestamp': '00:01:12.880',
        'end_timestamp': '00:01:17.000',
        'current_aoi_list': [5],
    },
    {
        'id': '9',
        'content': 'It was just a small 5cm by 5cm photo captured as 30k pixels.',
        'start_timestamp': '00:01:17.000',
        'end_timestamp': '00:01:24.440',
        'current_aoi_list': [5],
    },
    {
        'id': '10',
        'content': 'In 1989, a young French scientist Yann LeCun applied a back-propagation style learning algorithm.',
        'start_timestamp': '00:01:24.440',
        'end_timestamp': '00:01:32.520',
        'current_aoi_list': [6,7],
    },
    {
        'id': '11',
        'content': 'After working on the project for a few years, LeCun released LeNet-5—the first modern convolutional network that introduced some of the essential ingredients we still use in CNNs today.',
        'start_timestamp': '00:01:32.520',
        'end_timestamp': '00:01:44.240',
        'current_aoi_list': [6,7],
    },
    {
        'id': '12',
        'content': 'In 2006, the Pascal VOC project was launched.',
        'start_timestamp': '00:01:44.240',
        'end_timestamp': '00:01:49.760',
        'current_aoi_list': [8,9],
    },
    {
        'id': '13',
        'content': 'It provided a standardized dataset for object classification.',
        'start_timestamp': '00:01:49.760',
        'end_timestamp': '00:01:53.760',
        'current_aoi_list': [8,9],
    },
    {
        'id': '14',
        'content': 'The founders also ran an annual competition that allowed evaluating the performance of different methods for object class recognition.',
        'start_timestamp': '00:01:53.760',
        'end_timestamp': '00:02:01.680',
        'current_aoi_list': [8,9],
    },
    {
        'id': '15',
        'content': 'In 2012, a team from the University of Toronto entered a convolutional neural network model into an image classification competition and that changed everything. ',
        'start_timestamp': '00:02:01.680',
        'end_timestamp': '00:02:12.680',
        'current_aoi_list': [10,11],
    },
    {
        'id': '16',
        'content': 'The model, called AlexNet, similar to LeCun\'s LeNet-5, achieved an error rate of 16.4%, which overperformed all other methods at that time.',
        'start_timestamp': '00:02:12.680',
        'end_timestamp': '00:02:24.160',
        'current_aoi_list': [10,11],
    },
    {
        'id': '17',
        'content': 'This was a breakthrough moment for CNNs.',
        'start_timestamp': '00:02:24.160',
        'end_timestamp': '00:02:26.520',
        'current_aoi_list': [10,11],
    },
    {
        'id': '18',
        'content': 'However, convolutional neural networks have been around since the 1980s.',
        'start_timestamp': '00:02:26.520',
        'end_timestamp': '00:02:31.520',
        'current_aoi_list': [10,11],
    },
    {
        'id': '19',
        'content': 'So why did it take so long for them to become popular?',
        'start_timestamp': '00:02:31.520',
        'end_timestamp': '00:02:34.520',
        'current_aoi_list': [10,11],
    },
    {
        'id': '20',
        'content': 'Thanks to the development of Graphics Processing Units, we can parallelize the computation and significantly reduce the time needed for computation.',
        'start_timestamp': '00:02:34.520',
        'end_timestamp': '00:02:44.560',
        'current_aoi_list': [10,11],
    },
    {
        'id': '21',
        'content': 'Also, it was around 2012 when large, labeled, high-dimensional visual datasets became available to the computer vision research community.',
        'start_timestamp': '00:02:44.560',
        'end_timestamp': '00:02:53.600',
        'current_aoi_list': [10,11],
    },
    {
        'id': '22',
        'content': 'These two factors helped CNNs to boost.',
        'start_timestamp': '00:02:53.600',
        'end_timestamp': '00:02:57.600',
        'current_aoi_list': [10,11],
    },
    {
        'id': '23',
        'content': 'Here are a few common tasks that computer vision systems can be used for.',
        'start_timestamp': '00:02:57.600',
        'end_timestamp': '00:03:03.520',
        'current_aoi_list': [1], # Slide 3
    },
    {
        'id': '24',
        'content': 'The first common task is called Object classification.',
        'start_timestamp': '00:03:03.520',
        'end_timestamp': '00:03:06.060',
        'current_aoi_list': [2],
    },
    {
        'id': '25',
        'content': 'The system parses visual content and classifies the object on a photo/video to the defined category.',
        'start_timestamp': '00:03:06.060',
        'end_timestamp': '00:03:13.200',
        'current_aoi_list': [2],
    },
    {
        'id': '26',
        'content': 'For example, the system can find a cat when presented with the first image.',
        'start_timestamp': '00:03:13.200',
        'end_timestamp': '00:03:19.200',
        'current_aoi_list': [2],
    },
    {
        'id': '27',
        'content': 'The second figure shows the task called Object localization.',
        'start_timestamp': '00:03:19.200',
        'end_timestamp': '00:03:23.520',
        'current_aoi_list': [3],
    },
    {
        'id': '28',
        'content': 'This requires a bit more than the classification.',
        'start_timestamp': '00:03:23.520',
        'end_timestamp': '00:03:26.540',
        'current_aoi_list': [3],
    },
    {
        'id': '29',
        'content': 'Not only the system needs to generate the class label, it should also identify a bounding box that covers the detected object.',
        'start_timestamp': '00:03:26.540',
        'end_timestamp': '00:03:34.100',
        'current_aoi_list': [3],
    },
    {
        'id': '30',
        'content': 'Then the third figure shows the Object Detection task.',
        'start_timestamp': '00:03:34.100',
        'end_timestamp': '00:03:38.360',
        'current_aoi_list': [4],
    },
    {
        'id': '31',
        'content': 'This becomes more difficult as it requires the system to be able to process multiple objects in the image at the same time.',
        'start_timestamp': '00:03:38.360',
        'end_timestamp': '00:03:46.280',
        'current_aoi_list': [4],
    },
    {
        'id': '32',
        'content': 'The fourth task is called Object tracking.',
        'start_timestamp': '00:03:46.280',
        'end_timestamp': '00:03:49.120',
        'current_aoi_list': [5],
    },
    {
        'id': '33',
        'content': 'It can be considered object detection over video.',
        'start_timestamp': '00:03:49.120',
        'end_timestamp': '00:03:52.120',
        'current_aoi_list': [5],
    },
    {
        'id': '34',
        'content': 'The system takes an initial set of multiple objects detected and then tracks each object as they move around frames in a video while maintaining the identity of each object.',
        'start_timestamp': '00:03:52.120',
        'end_timestamp': '00:04:03.000',
        'current_aoi_list': [5],
    },
    {
        'id': '35',
        'content': 'Before we discuss how computers process images, we need to understand how images are stored in computers.',
        'start_timestamp': '00:04:03.000',
        'end_timestamp': '00:04:11.080',
        'current_aoi_list': [1], # Slide 4
    },
    {
        'id': '36',
        'content': 'A pixel or picture element is the smallest addressable element in the image.',
        'start_timestamp': '00:04:11.080',
        'end_timestamp': '00:04:16.280',
        'current_aoi_list': [2,3,4],
    },
    {
        'id': '37',
        'content': 'For each pixel, it is assigned a color when we are dealing with color images.',
        'start_timestamp': '00:04:16.280',
        'end_timestamp': '00:04:21.320',
        'current_aoi_list': [2,3,4],
    },
    {
        'id': '38',
        'content': 'Here we show an example of a gray-scale image.',
        'start_timestamp': '00:04:21.320',
        'end_timestamp': '00:04:25.320',
        'current_aoi_list': [2,3],
    },
    {
        'id': '39',
        'content': 'In computers, the image is stored in a format similar to a table.',
        'start_timestamp': '00:04:25.320',
        'end_timestamp': '00:04:29.100',
        'current_aoi_list': [2,3,4],
    },
    {
        'id': '40',
        'content': 'Each row and column specifies a pixel, and each pixel is associated with a value representing the level of brightness.',
        'start_timestamp': '00:04:29.100',
        'end_timestamp': '00:04:36.600',
        'current_aoi_list': [3,4],
    },
    {
        'id': '41',
        'content': 'For gray-scale images, the value to each pixel is just the brightness at each pixel.',
        'start_timestamp': '00:04:36.600',
        'end_timestamp': '00:04:42.720',
        'current_aoi_list': [3,4],
    },
    {
        'id': '42',
        'content': 'But for colorful images, each pixel contains three numbers representing the red, green, and blue values of each color.',
        'start_timestamp': '00:04:42.720',
        'end_timestamp': '00:04:50.200',
        'current_aoi_list': [4,5],
    },
    {
        'id': '43',
        'content': 'For simplicity, we will mainly discuss grey-scale images in the following slides.',
        'start_timestamp': '00:04:50.200',
        'end_timestamp': '00:04:56.560',
        'current_aoi_list': [2,3,4],
    },
]

video_5_transcript = [
    {
        'id': '0',
        'content': 'In 2019, NHS Foundation Trust provided data on 1.6 million patients to Alphabet\'s DeepMind, without taking any permission from the patients to share their private data.',
        'start_timestamp': '00:00:00.520',
        'end_timestamp': '00:00:12.360',
        'current_aoi_list': [2],
    },
    {
        'id': '1',
        'content': 'Keeping in view the privacy concerns of patients, Google canceled the plan to broadcast chest X-ray scans on account of concerns of patients as they were carrying personally identifiable information.',
        'start_timestamp': '00:00:12.360',
        'end_timestamp': '00:00:25.680',
        'current_aoi_list': [2],
    },
    {
        'id': '2',
        'content': 'The second example is a data set containing above 10 million images of 100,000 celebrities created by Microsoft called MS Celeb.',
        'start_timestamp': '00:00:25.680',
        'end_timestamp': '00:00:34.420',
        'current_aoi_list': [3],
    },
    {
        'id': '3',
        'content': 'This has been removed since celebrities expressed their concerns that they were not even aware of being included.',
        'start_timestamp': '00:00:34.420',
        'end_timestamp': '00:00:40.180',
        'current_aoi_list': [3],
    },
    {
        'id': '4',
        'content': 'Besides this unconscious revealing of personal data, there is a type of personal data that we are uploading on social media by ourselves.',
        'start_timestamp': '00:00:40.180',
        'end_timestamp': '00:00:49.280',
        'current_aoi_list': [4],
    },
    {
        'id': '5',
        'content': 'For instance, we visit a restaurant or a store and take several images of the food or product we like and post them online.',
        'start_timestamp': '00:00:49.280',
        'end_timestamp': '00:00:56.220',
        'current_aoi_list': [4],
    },
    {
        'id': '6',
        'content': 'Most of this data is transferred to cloud computers that have considerably enhanced the probability of tracking this personal information.',
        'start_timestamp': '00:00:56.220',
        'end_timestamp': '00:01:04.488',
        'current_aoi_list': [4],
    },
    {
        'id': '7',
        'content': 'The first concern is called Data persistence, where data exists longer than the human subjects that created it.',
        'start_timestamp': '00:01:04.488',
        'end_timestamp': '00:01:10.400',
        'current_aoi_list': [2], # Slide 2
    },
    {
        'id': '8',
        'content': 'The images of your car photo may store for years and even you have forgotten its existence.',
        'start_timestamp': '00:01:10.400',
        'end_timestamp': '00:01:16.280',
        'current_aoi_list': [2],
    },
    {
        'id': '9',
        'content': 'The second concern is called Data repurposing, which means data are being used beyond their originally imagined purpose.',
        'start_timestamp': '00:01:16.280',
        'end_timestamp': '00:01:24.160',
        'current_aoi_list': [3],
    },
    {
        'id': '10',
        'content': 'For example, in a decade\'s time, parking habits may be part of the data used by grocery retailers to analyze an individual\'s preference for shopping.',
        'start_timestamp': '00:01:24.160',
        'end_timestamp': '00:01:33.320',
        'current_aoi_list': [3],
    },
    {
        'id': '11',
        'content': 'Finally, the concern called Data spillovers is associated with the case when data are collected on people who are not the target of data collection.',
        'start_timestamp': '00:01:33.320',
        'end_timestamp': '00:01:43.800',
        'current_aoi_list': [4],
    },
    {
        'id': '12',
        'content': 'The photo may record other people and they may be identifiable through facial recognition, or incidentally captured cars may be identifiable through license plate databases.',
        'start_timestamp': '00:01:43.800',
        'end_timestamp': '00:01:54.811',
        'current_aoi_list': [4],
    },
    {
        'id': '13',
        'content': 'As concerns grow, many Privacy-preserving techniques that can largely conceal the identity of persons or groups are now a standard staple in AI systems.',
        'start_timestamp': '00:01:54.811',
        'end_timestamp': '00:02:04.480',
        'current_aoi_list': [1], # Slide 3
    },
    {
        'id': '14',
        'content': 'These techniques must balance the need for privacy and the usability of the system.',
        'start_timestamp': '00:02:04.480',
        'end_timestamp': '00:02:09.680',
        'current_aoi_list': [1],
    },
    {
        'id': '15',
        'content': 'We first discuss the technology that is called Differential privacy.',
        'start_timestamp': '00:02:09.680',
        'end_timestamp': '00:02:13.640',
        'current_aoi_list': [1],
    },
    {
        'id': '16',
        'content': 'Before trying to understand this method, let us consider this example.',
        'start_timestamp': '00:02:13.640',
        'end_timestamp': '00:02:18.360',
        'current_aoi_list': [2,3,4,5,6],
    },
    {
        'id': '17',
        'content': 'Assume your parent is trying to get the score of your final exam this semester, but your teacher is trying to keep the privacy of students.',
        'start_timestamp': '00:02:18.360',
        'end_timestamp': '00:02:26.300',
        'current_aoi_list': [2,3],
    },
    {
        'id': '18',
        'content': 'The only information your parent can receive is the average, median and some other general information about the score.',
        'start_timestamp': '00:02:26.300',
        'end_timestamp': '00:02:33.180',
        'current_aoi_list': [2,4],
    },
    {
        'id': '19',
        'content': 'In this way, your parent learns some information about the final, but your privacy is preserved.',
        'start_timestamp': '00:02:33.180',
        'end_timestamp': '00:02:39.040',
        'current_aoi_list': [2,4],
    },
    {
        'id': '20',
        'content': 'This is the idea used by Differential privacy: the information requester will not be able to be 100% sure to infer any specific individual.',
        'start_timestamp': '00:02:39.040',
        'end_timestamp': '00:02:49.480',
        'current_aoi_list': [1,2,4],
    },
    {
        'id': '21',
        'content': 'But please note this protection is offered by the number of students in your class.',
        'start_timestamp': '00:02:49.480',
        'end_timestamp': '00:02:53.100',
        'current_aoi_list': [2,4],
    },
    {
        'id': '22',
        'content': 'If the class contains a hundred people, each person\'s score contributes just 1%.',
        'start_timestamp': '00:02:53.100',
        'end_timestamp': '00:02:59.260',
        'current_aoi_list': [2,4],
    },
    {
        'id': '23',
        'content': 'However, if the class contains scores from only a single person, that person\'s individual data contributes to 100% of the class data.',
        'start_timestamp': '00:02:59.260',
        'end_timestamp': '00:03:08.360',
        'current_aoi_list': [2,4],
    },
    {
        'id': '24',
        'content': 'The key insight of differential privacy is that as the query is made on the data of fewer and fewer people, more noise needs to be added to the result to produce the same amount of privacy.',
        'start_timestamp': '00:03:08.360',
        'end_timestamp': '00:03:19.280',
        'current_aoi_list': [2,3,4,5,6],
    },
    {
        'id': '25',
        'content': 'In this example, if your parent asks the average score of students with your last name, to protect your privacy, your teacher must add some noise in the result.',
        'start_timestamp': '00:03:19.280',
        'end_timestamp': '00:03:29.320',
        'current_aoi_list': [2,5,6],
    },
    {
        'id': '26',
        'content': 'Otherwise, your scores will very likely be identified.',
        'start_timestamp': '00:03:29.320',
        'end_timestamp': '00:03:32.220',
        'current_aoi_list': [2,5,6],
    },
    {
        'id': '27',
        'content': 'Though this partially solves the problem, individuals are not identified, but the data we uploaded to the server may suffer from Data persistence and spillover.',
        'start_timestamp': '00:03:32.220',
        'end_timestamp': '00:03:42.240',
        'current_aoi_list': [1], # Slide 4
    },
    {
        'id': '28',
        'content': 'A solution to this problem is to encrypt the data.',
        'start_timestamp': '00:03:42.240',
        'end_timestamp': '00:03:46.120',
        'current_aoi_list': [1],
    },
    {
        'id': '29',
        'content': 'Encryption is the process of encoding information.',
        'start_timestamp': '00:03:46.120',
        'end_timestamp': '00:03:49.160',
        'current_aoi_list': [1,2],
    },
    {
        'id': '30',
        'content': 'This process converts the original representation of the information, known as plaintext, into an alternative form known as ciphertext.',
        'start_timestamp': '00:03:49.160',
        'end_timestamp': '00:03:58.240',
        'current_aoi_list': [2],
    },
    {
        'id': '31',
        'content': 'Ideally, only authorized parties can decipher a ciphertext back to plaintext and access the original information.',
        'start_timestamp': '00:03:58.240',
        'end_timestamp': '00:04:05.018',
        'current_aoi_list': [2],
    },
    {
        'id': '32',
        'content': 'However, this stops us from utilizing any service provided by the system.',
        'start_timestamp': '00:04:05.018',
        'end_timestamp': '00:04:10.220',
        'current_aoi_list': [2],
    },
    {
        'id': '33',
        'content': 'The privacy is preserved, but we again receive nothing helpful.',
        'start_timestamp': '00:04:10.220',
        'end_timestamp': '00:04:14.000',
        'current_aoi_list': [2],
    },
    {
        'id': '34',
        'content': 'Scientists then try to find a way to encrypt the data, yet still allow computation.',
        'start_timestamp': '00:04:14.000',
        'end_timestamp': '00:04:19.680',
        'current_aoi_list': [2],
    },
    {
        'id': '35',
        'content': 'This is termed homomorphic encryption.',
        'start_timestamp': '00:04:19.680',
        'end_timestamp': '00:04:22.080',
        'current_aoi_list': [6],
    },
    {
        'id': '36',
        'content': 'It permits users to perform computations on its encrypted data without first decrypting it.',
        'start_timestamp': '00:04:22.080',
        'end_timestamp': '00:04:29.640',
        'current_aoi_list': [6],
    },
    {
        'id': '37',
        'content': 'These computations are left in an encrypted form.',
        'start_timestamp': '00:04:29.640',
        'end_timestamp': '00:04:32.280',
        'current_aoi_list': [6],
    },
    {
        'id': '38',
        'content': 'When decrypted, the result is identical to that produced had the operations been performed on the unencrypted data.',
        'start_timestamp': '00:04:32.280',
        'end_timestamp': '00:04:39.180',
        'current_aoi_list': [6],
    },
    {
        'id': '39',
        'content': 'Homomorphic refers to a special correspondence, and in this context, it means the calculation on encrypted data is the same when it is being decrypted.',
        'start_timestamp': '00:04:39.180',
        'end_timestamp': '00:04:48.240',
        'current_aoi_list': [6],
    },
    {
        'id': '40',
        'content': 'For example, let\'s consider the easiest encryption called the Caeser cipher, which replaces a letter with another letter with a fixed number of positions down the alphabet.',
        'start_timestamp': '00:04:48.240',
        'end_timestamp': '00:04:59.760',
        'current_aoi_list': [3,4],
    },
    {
        'id': '41',
        'content': 'For example, with a shift of 3, “A” will be replaced by “D” and “B” will be replaced by “E”. Letter “Z” will be replaced by “C.”',
        'start_timestamp': '00:04:59.760',
        'end_timestamp': '00:05:08.165',
        'current_aoi_list': [4],
    },
    {
        'id': '42',
        'content': 'Consider our calculation is to concatenate two words.',
        'start_timestamp': '00:05:08.165',
        'end_timestamp': '00:05:12.000',
        'current_aoi_list': [5],
    },
    {
        'id': '43',
        'content': 'The encrypted words are uploaded to some remote computer for this computation, and the result is transmitted back.',
        'start_timestamp': '00:05:12.000',
        'end_timestamp': '00:05:19.200',
        'current_aoi_list': [5],
    },
    {
        'id': '44',
        'content': 'We then decipher the result and find this is just the result if we conduct the same operation with the plain text.',
        'start_timestamp': '00:05:19.200',
        'end_timestamp': '00:05:25.160',
        'current_aoi_list': [5],
    },
    {
        'id': '45',
        'content': 'But the good thing is the remote computer can not tell what is being transmitted.',
        'start_timestamp': '00:05:25.160',
        'end_timestamp': '00:05:29.160',
        'current_aoi_list': [5],
    },
    {
        'id': '46',
        'content': 'In this way, both privacy and utility are preserved.',
        'start_timestamp': '00:05:29.160',
        'end_timestamp': '00:05:34.160',
        'current_aoi_list': [5],
    },
]



video_transcript_dict = {'video_1':video_1_transcript,'video_2':video_2_transcript,'video_3':video_3_transcript,'video_4':video_4_transcript,'video_5':video_5_transcript}

# Important Note: the list element in slide_timestamp_start_dict must be sorted!
slide_timestamp_start_dict = {
    'video_1': [0,29.595,223.59,259.5],
    'video_2': [0,108.68,205.12],
    'video_3': [0,77.12,248.84],
    'video_4': [0,31.228,177.6,243.0],
    'video_5': [0,64.488,114.811,212.22]
}

question_id_map_slide_dict = {
    'video_1': {0: [1,2], 1: [3,4,5,6,7,8], 2: [9,10,11], 3: [12]},
    'video_2': {0: [1], 1: [2,3,4,5,6,7,8], 2: [9,10,11]},
    'video_3': {0: [1,2,3], 1: [4,5,6,7,8], 2: [9,10,11]},
    'video_4': {0: [1,2], 1: [3,4,5,6,7], 2: [8,9,10,11], 3: [12]},
    'video_5': {0: [1,2,3], 1: [4,5,6,7], 2: [9], 3: [8,10,11,12]}
}

slide_map_question_id_dict = {
    'video_1': {1: 0, 2: 0, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 2, 10: 2, 11: 2, 12: 3},
    'video_2': {1: 0, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 2, 10: 2, 11: 2},
    'video_3': {1: 0, 2: 0, 3: 0, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 2, 10: 2, 11: 2},
    'video_4': {1: 0, 2: 0, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 2, 9: 2, 10: 2, 11: 2, 12: 3},
    'video_5': {1: 0, 2: 0, 3: 0, 4: 1, 5: 1, 6: 1, 7: 1, 8: 3, 9: 2, 10: 3, 11: 3, 12: 3},
}

slide_summary_dict = {
    'video_1': {0: 'What is AI and AI applications.', 1: 'AI History.', 2: 'AI Definition and classification.', 3: 'Three ways of AI learning.'},
    'video_2': {0: 'Supervised learning definition and demonstration.', 1: 'Features and labels in supervised learning.', 2: 'How supervised learning updates the model from features and labels.'},
    'video_3': {0: 'Explanation of unsupervised learning.', 1: 'Explanations of anomaly detection.', 2: 'Explanations of clustering.'},
    'video_4': {0: 'Introduction of computer vision.', 1: 'Computer vision history.', 2: 'Common tasks in computer vision.', 3: 'Image formats in computers.'},
    'video_5': {0: 'Case study of AI and privacy.', 1: 'Three types of privacy problems in AI.', 2: 'One AI privacy solution: differential privacy.', 3: 'One AI privacy solution: encryption.'},
}
